---
- hosts: all
  vars:
    log_dir: "/var/www/logs"

    node_version: "0.12.0"
    node_prefix: "node-v{{node_version}}"
    node_tarball: "{{node_prefix}}-linux-x64.tar.gz"
    node_path: "/usr/local"

  vars_files:
    - [ "../vars.yml", "../vars.default.yml" ]
  roles:
    - init
    - nodejs
    - app